name: Kiel
favicon: null
layout_spectrum: 0.9426523
typography_spectrum: 0.890681
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.2058342
  lightness: 0.3548387
  saturation: 0.5286738
  rhythmicContrast: 0.6541219
purpose: []
